### ISSUE TITLE
Code Licence?

### ISSUE THREAD

**Issue by paddatrapper** [prt459/Arduino_si5351_VFO_Controller_Keyer#4]
What is the licence you are releasing the code in this repo under? As it stands, with no licence, it defaults to All Rights Reserved - meaning that people are not allowed to use, distribute or modify the code. 

For a strong copy-left licence (Allow use, modification, etc and require all things linking against this code to be licenced the same), I recommend the GPL-3+. If you would prefer a more permissive licence, I would recommend the MIT licence. More details and help choosing a licence can be found here - https://choosealicense.com/

**Comment by prt459** [comment]
Thankyou for pointing this out, and for supplying the URL to help me understand the options.  I choose the GNU GPLv3 license, the text of which I will place in a license.txt file in the repo.  A number of people have contacted me to use this code in home maker projects and for support.  That's what I hoped for.  There are also some forked repos.   If this code appeared in a kit transceiver sold for profit, or in a commercial product, I would like to know.  It is not particularly difficult or original code but it does represent 'a work' and a considerable number of hours.

**Comment by paddatrapper** [comment]
Thanks! It certainly looks like it took a considerable number of hours to develop.

I am busy working on a bench-top transceiver based on your Summit Prowler 6. Thank you for being so open with the designs and code. It is much appreciated!

**Comment by paddatrapper** [comment]
Fixed in 0b89c70
